### PR TITLE
refactor footer for mobile view and homepage padding fix

### PR DESCRIPTION
**Pull request by elasticSzyszko**
Description:
added classnames for footer and modified css for footer to display nicer in mobile. Small padding adjustment to home page for some mobile views.

@dusanradovanovic @shaunmaharaj @epmkelly Please review

Tests:

- [X] Smoke tests (mvn clean install -Dcucumber.options="--tags @smoketest" from test)
- [X] Manual tests did comparisons on different resolutions

Documentation:

- [ ] Requires documentation updates: none

### CODE REVIEW

**Comment by dusanradovanovic** [comment]
Footer font sizes seem to be off in all tree modes:

image

image

image

**Comment by dusanradovanovic** [comment]
I think the footer is fine the way it is now, just needs icons for social links and better separation between the sections in mobile view.

screen shot 2018-10-03 at 1 06 31 pm

**Comment by elasticSzyszko** [comment]
image

**Comment by elasticSzyszko** [comment]
image

**Comment by elasticSzyszko** [comment]
I've gone by the mock ups in term of font size and the look Do we want to deviate?

**Comment by shaunmaharaj** [comment]
The layout look perfect! Thank you @elasticSzyszko!
My only concern are the font sizes. We may have to deviate a bit from the mockups as they're rendered differently upon size changes.

**Comment by elasticSzyszko** [comment]
font sizes increased for mobile and few paddings changes added

**Pull request merged**
