### PR TITLE
Fix banners in production build.

### PR DESCRIPTION
**Pull request by aChanEP**
Description:

This ticket fixes issue #384.

Gets rid of clashing default style in reset.less with bootstraps default styling.

Linting:

- [ ] No linting errors

Tests:

- [ ] E2E tests (npm test run with `e2e`)
- [ ] Manual tests

Did a comparison of local and production build.  
Notice that the styles align.

Documentation:

- [ ] Requires documentation updates

### CODE REVIEW

**Comment by shaunmaharaj** [comment]
@aChanEP please resolve conflicts then I'll merge

**Comment by shaunmaharaj** [comment]
@aChanEP I just noticed you already included this in your other PR. Please close if it's no longer needed.

**Comment by aChanEP** [comment]
Nope this change should be independent of any PR's.  Which PR are you referring too?

**Comment by shaunmaharaj** [comment]
@aChanEP ah, I see the change. I'll close this PR and push in another for you to keep it clean 😄

**Comment by aChanEP** [comment]
Sounds good thanks!

**Pull request closed without merging**
