### PR TITLE
Rs 442

### PR DESCRIPTION
**Pull request by aChanEP**
Description:

This ticket resolves the issue described here: https://github.com/elasticpath/react-pwa-reference-storefront/issues/330

All images have been placed into the original CRA project.  This is due to the fact that it should be the client who is consuming the components that should be providing the images.

All the top level styles and constants have been deleted inside the components folder.  The styles folder under the original CRA project is now being used.  Again it should be the client of the components who should provide the styles.

Linting:

- [ ] No linting errors

Tests:

- [ ] E2E tests (npm test run with `e2e`)
- [ ] Manual tests

Documentation:

- [ ] Requires documentation updates

1.) Change the `common.less` file constants and notice changes.  (Other common.less has been deleted to avoid confusion)
2.) Try and change an image under the `app` directory and notice changes in the images that are bundled.

### CODE REVIEW

**Comment by shaunmaharaj** [comment]
@aChanEP As part of this PR, we'll have to update the version of the components in `react-pwa-reference-storefront/components/package.json` so the updated components are pushed to npm. The current version is `1.1.8`, and should be incremented to `1.1.9`. In the future we have to automate this step though.

**Comment by aChanEP** [comment]
Will have it updated in a few moments.  Thanks!

**Comment by aChanEP** [comment]
updated!

**Comment by aChanEP** [comment]
resolved

**Pull request merged**
