### PR TITLE
Footer redesign

### PR DESCRIPTION
**Pull request by dusanradovanovic**
Description:
Simplification and minor redesign of the footer to match Zeplin designs

Tests:

- [x] Smoke tests (mvn clean install -Dcucumber.options="--tags @smoketest" from test)
- [x] Manual tests

Documentation:

- [ ] Requires documentation updates

### CODE REVIEW

**Comment by dusanradovanovic** [comment]
image

image

**Comment by elasticSzyszko** [comment]
image

**Comment by elasticSzyszko** [comment]
1) non-header text in mocks is #dedefc. 
2) "find us online" replaced with Vestri in tablet/desktop and not visible in mobile?
3) for mobile spacing is not that compact in mocks, but this looks pretty good too.

**Comment by dusanradovanovic** [comment]
Amazing attention to detail @elasticSzyszko ! I would never notice the different color!

Since this one is already merged I've opened a new PR where I've addressed these issues: https://github.com/elasticpath/react-pwa-reference-storefront/pull/60

**Pull request merged**
