### PR TITLE
implement new design of quantity picker

### PR DESCRIPTION
**Pull request by yulia-dnistrian**
Description:

Linting:

- [x] No linting errors

Component Updates:

- [x] Component package requires update on npm [@elasticpath/store-components](https://www.npmjs.com/package/@elasticpath/store-components)

Tests:

- [x] E2E tests (npm test run with `e2e`)
- [x] Manual tests

Documentation:

- [ ] Requires documentation updates

### CODE REVIEW

**Comment by BonnieEP** [comment]
Screen Shot 2020-02-27 at 11 47 53 AM
Screen Shot 2020-02-27 at 11 47 57 AM

Hi Yulia 

This interaction looks good but the icons aren't centered in the buttons. Are you able to center them?

**Comment by yulia-dnistrian** [comment]
@BonnieEP Thanks for noticing this. I updated PR, please, check if everything is correct.

**Comment by BonnieEP** [comment]
@yulia-dnistrian the "+" alignment still looks a bit off, can we try the using vertical-align property? 

.input-group-btn .quantity-right-plus:hover, .input-group-btn .quantity-left-minus:hover {
vertical-align: -webkit-baseline-middle;
}

**Comment by shaunmaharaj** [comment]
@yulia-dnistrian can you please address the conflicts with this PR?

**Comment by BonnieEP** [comment]
Looks good @yulia-dnistrian except for on mobile the component doesn't show the up down carets https://projects.invisionapp.com/dsm/elastic-path/general/asset/icons/5e59b475ed3490c4d2a93cc8

**Comment by shaunmaharaj** [comment]
> Looks good @yulia-dnistrian except for on mobile the component doesn't show the up down carets https://projects.invisionapp.com/dsm/elastic-path/general/asset/icons/5e59b475ed3490c4d2a93cc8

Is this link the correct asset? It's directed to the info icon in dsm.

**Comment by BonnieEP** [comment]
Looks good @yulia-dnistrian. @shaunmaharaj can we create another task for mobile to increase the size of controls? I'd like to use the @media only CSS to target only mobile devices (under 600px) with larger controls for touch https://www.w3schools.com/cssref/css3_pr_mediaquery.asp

**Comment by shaunmaharaj** [comment]
@BonnieEP sure, that makes sense. We can work on this in a separate task. 

Thanks for the great work on this one @yulia-dnistrian & @BonnieEP!!

**Pull request merged**
